

name: Build, Unit Test, and Deploy to Google Cloud e2 Ubuntu instance

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build and publish .NET Core app
      run: |
        dotnet restore
        dotnet publish -c Release -o out

    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'

    - name: 'Use gcloud CLI'
      run: 'gcloud info'

    - id: 'compute-ssh'
      uses: 'google-github-actions/ssh-compute@v0'
      with:
        instance_name: '${{ secrets.GCP_INSTANCE_NAME }}'
        zone: '${{ secrets.GCP_ZONE }}'
        ssh_private_key: '${{ secrets.SSH_PRIVATE_KEY }}'
        user: '${{ secrets.GCP_USER }}'
        command: >
          cd /home/ripman3/telegram_bots/pokefusion
          git pull
          dotnet publish -c Release -o published
          cd published
          dotnet PokeFusionBot.dll

    - name: Access logs
      id: 'logs'
      run: |-
        echo '${{ steps.compute-ssh.outputs.stdout }}'
        echo '${{ steps.compute-ssh.outputs.stderr }}'