

name: Deploy to Google Cloud e2 Ubuntu instance

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build and publish .NET Core app
      run: |
        dotnet restore
        dotnet publish -c Release -o out

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: pokefusion-telegrambot
        export_default_credentials: true 

    - name: Deploy
      run: |
        ssh -o StrictHostKeyChecking=no ripman3@34.67.246.160 'bash -s' << EOF
          echo "${{ secrets.TELEGRAM_BOT_TOKEN }}" > /telegram_bots/pokefusion/bot_token.txt
          cd /telegram_bots/pokefusion
          git pull origin main
          dotnet publish -c Release -o published
          cd published
          dotnet PokeFusionBot.dll
        EOF
        

