

name: Deploy to Google Cloud e2 Ubuntu instance

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build and publish .NET Core app
      run: |
        dotnet restore
        dotnet publish -c Release -o out

    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'

    - name: 'Use gcloud CLI'
      run: 'gcloud info'

    - id: 'compute-ssh'
      uses: 'google-github-actions/ssh-compute@v0'
      with:
        instance_name: 'telegram-bot-1'
        zone: 'us-central1-a'
        ssh_private_key: '${{ secrets.SSH_PRIVATE_KEY }}'
        run: |
          cd /telegram_bots/pokefusion
          git pull origin main
          dotnet publish -c Release -o published
          cd published
          dotnet PokeFusionBot.dll
