

name: Deploy to Google Cloud e2 Ubuntu instance

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build and publish .NET Core app
      run: |
        dotnet restore
        dotnet publish -c Release -o out

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.4.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }} 
        
    - name: Deploy code
        run: |
          ssh -o StrictHostKeyChecking=no ripman3@34.67.246.160 'bash -s' << EOF
            echo "${{ secrets.TELEGRAM_BOT_TOKEN }}" > /telegram_bots/pokefusion/bot_token.txt
            cd /telegram_bots/pokefusion
            git pull origin main
            dotnet publish -c Release -o published
            cd published
            dotnet PokeFusionBot.dll
          EOF
        

