

name: Build, Unit Test, and Deploy to Google Cloud e2 Ubuntu instance

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'

    - name: 'Use gcloud CLI'
      run: 'gcloud info'

    - id: 'compute-ssh'
      uses: 'google-github-actions/ssh-compute@v0'
      with:
        instance_name: '${{ secrets.GCP_INSTANCE_NAME }}'
        zone: '${{ secrets.GCP_ZONE }}'
        ssh_private_key: '${{ secrets.SSH_PRIVATE_KEY }}'
        user: '${{ secrets.GCP_USER }}'
        command: |
          pkill -f "PokeFusionBot"
          cd /home/ripman3/telegram_bots/pokefusion/PokeFusionBot
          git pull
          dotnet build
          dotnet publish -c Release -r linux-x64 --self-contained true
          cd PokeFusionBot/bin/Release/net7.0/linux-x64/publish
          echo "${{ secrets.TELEGRAM_BOT_TOKEN }}" > token.txt
          nohup ./PokeFusionBot
          exit

    - name: Access logs
      id: 'logs'
      run: |-
        echo '${{ steps.compute-ssh.outputs.stdout }}'
        echo '${{ steps.compute-ssh.outputs.stderr }}'